export type Difficulty = 'Beginner' | 'Intermediate' | 'Advanced';
export type Category = 'Bags' | 'Amigurumi' | 'Blankets' | 'Hats' | 'Scarves' | 'Home Decor';

export interface LibraryPattern {
  id: string;
  title: string;
  titleAr: string;
  category: Category;
  categoryAr: string;
  difficulty: Difficulty;
  difficultyAr: string;
  hours: number;
  yarnType: string;
  yarnTypeAr: string;
  hookSize: string;
  finishedSize: string;
  finishedSizeAr: string;
  isPremium: boolean;
  favorites: number;
  createdAt: string; // ISO date for sorting
  image: string;
  gallery: string[];
  description: string;
  descriptionAr: string;
  materials: string[];
  materialsAr: string[];
  yarnRecommendations: string[];
  yarnRecommendationsAr: string[];
}

export const libraryPatterns: LibraryPattern[] = [
  {
    id: 'floral-market-tote',
    title: 'Floral Market Tote',
    titleAr: 'حقيبة السوق الزهرية',
    category: 'Bags',
    categoryAr: 'الحقائب',
    difficulty: 'Beginner',
    difficultyAr: 'مبتدئ',
    hours: 6,
    yarnType: 'Cotton DK',
    yarnTypeAr: 'قطن DK',
    hookSize: '4.0mm',
    finishedSize: '35 × 40 cm',
    finishedSizeAr: '35 × 40 سم',
    isPremium: false,
    favorites: 1240,
    createdAt: '2025-06-15',
    image: 'https://images.pexels.com/photos/30224898/pexels-photo-30224898.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop',
    gallery: [
      'https://images.pexels.com/photos/30224898/pexels-photo-30224898.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/30859912/pexels-photo-30859912.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/30224895/pexels-photo-30224895.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
    ],
    description: 'A sturdy, everyday market tote with delicate floral embroidery. Perfect for beginners who want to practice single crochet while creating a practical, beautiful bag.',
    descriptionAr: 'حقيبة تسوق متينة للاستخدام اليومي مع تطريز زهري دقيق. مثالية للمبتدئين الذين يريدون التدرب على الغرزة الفردية أثناء صنع حقيبة عملية وجميلة.',
    materials: ['Cotton DK yarn (320 m)', '4.0mm crochet hook', 'Stitch markers', 'Tapestry needle', 'Scissors'],
    materialsAr: ['خيط قطن DK (320 م)', 'إبرة كروشيه 4.0mm', 'علامات غرز', 'إبرة خياطة', 'مقص'],
    yarnRecommendations: ['Lion Brand 24/7 Cotton', 'Paintbox Yarns Cotton DK', 'Sugar Bush Cotton'],
    yarnRecommendationsAr: ['Lion Brand 24/7 قطن', 'Paintbox قطن DK', 'Sugar Bush قطن'],
  },
  {
    id: 'leather-accent-backpack',
    title: 'Leather Accent Backpack',
    titleAr: 'حقيبة ظهر بلمسات جلدية',
    category: 'Bags',
    categoryAr: 'الحقائب',
    difficulty: 'Intermediate',
    difficultyAr: 'متوسط',
    hours: 12,
    yarnType: 'Worsted',
    yarnTypeAr: 'Worsted',
    hookSize: '5.0mm',
    finishedSize: '30 × 38 cm',
    finishedSizeAr: '30 × 38 سم',
    isPremium: true,
    favorites: 890,
    createdAt: '2025-07-20',
    image: 'https://images.pexels.com/photos/10820406/pexels-photo-10820406.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop',
    gallery: [
      'https://images.pexels.com/photos/10820406/pexels-photo-10820406.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/10820408/pexels-photo-10820408.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/10820410/pexels-photo-10820410.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
    ],
    description: 'A sophisticated backpack combining crochet texture with genuine leather accents. Features an adjustable strap and magnetic closure.',
    descriptionAr: 'حقيبة ظهر أنيقة تجمع بين ملمس الكروشيه ولمسات الجلد الأصلي. تتميز بحزام قابل للتعديل وإغلاق مغناطيسي.',
    materials: ['Worsted yarn (450 m)', '5.0mm crochet hook', 'Leather straps & closures', 'Stitch markers', 'Tapestry needle', 'Lining fabric'],
    materialsAr: ['خيط Worsted (450 م)', 'إبرة كروشيه 5.0mm', 'أحزمة وأقفال جلدية', 'علامات غرز', 'إبرة خياطة', 'قماش بطانة'],
    yarnRecommendations: ['Lion Brand Wool Ease', 'Bernat Softee Chunky', 'Red Heart Soft'],
    yarnRecommendationsAr: ['Lion Brand Wool Ease', 'Bernat Softee Chunky', 'Red Heart Soft'],
  },
  {
    id: 'colorful-amigurumi-pals',
    title: 'Colorful Amigurumi Pals',
    titleAr: 'أصدقاء الأميغورومي الملونة',
    category: 'Amigurumi',
    categoryAr: 'أميغورومي',
    difficulty: 'Intermediate',
    difficultyAr: 'متوسط',
    hours: 9,
    yarnType: 'Cotton Sport',
    yarnTypeAr: 'قطن رفيع',
    hookSize: '3.0mm',
    finishedSize: '12 cm tall',
    finishedSizeAr: '12 سم ارتفاعًا',
    isPremium: false,
    favorites: 2100,
    createdAt: '2025-05-10',
    image: 'https://images.pexels.com/photos/38705858/pexels-photo-38705858.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop',
    gallery: [
      'https://images.pexels.com/photos/38705858/pexels-photo-38705858.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/38679697/pexels-photo-38679697.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/38718822/pexels-photo-38718822.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
    ],
    description: 'A set of adorable amigurumi animal friends — a dog, cat, and bunny. Great for gifts, nursery decor, or keychain charms.',
    descriptionAr: 'مجموعة من أصدقاء الأميغورومي الحيوانيين اللطيفين — كلب وقطة وأرنب. رائعة كهدية أو ديكور غرفة الأطفال أو ميدالية مفاتيح.',
    materials: ['Cotton Sport yarn (180 m total)', '3.0mm crochet hook', 'Polyfill stuffing', 'Safety eyes 8mm', 'Stitch markers', 'Tapestry needle'],
    materialsAr: ['خيط قطن رفيع (180 م)', 'إبرة كروشيه 3.0mm', 'حشوة بولي فيل', 'عيون أمان 8mm', 'علامات غرز', 'إبرة خياطة'],
    yarnRecommendations: ['DMC Natura Just Cotton', 'Scheepjes Catona', 'Paintbox Yarns Cotton Aran'],
    yarnRecommendationsAr: ['DMC Natura قطن', 'Scheepjes Catona', 'Paintbox قطن Aran'],
  },
  {
    id: 'tea-time-bunny',
    title: 'Tea Time Bunny',
    titleAr: 'أرنب وقت الشاي',
    category: 'Amigurumi',
    categoryAr: 'أميغورومي',
    difficulty: 'Beginner',
    difficultyAr: 'مبتدئ',
    hours: 5,
    yarnType: 'Cotton DK',
    yarnTypeAr: 'قطن DK',
    hookSize: '3.5mm',
    finishedSize: '18 cm tall',
    finishedSizeAr: '18 سم ارتفاعًا',
    isPremium: false,
    favorites: 1560,
    createdAt: '2025-07-01',
    image: 'https://images.pexels.com/photos/7487646/pexels-photo-7487646.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop',
    gallery: [
      'https://images.pexels.com/photos/7487646/pexels-photo-7487646.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/16228950/pexels-photo-16228950.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/38745727/pexels-photo-38745727.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
    ],
    description: 'A sweet bunny toy perfect for tea parties and cozy afternoons. Beginner-friendly with step-by-step photo tutorials.',
    descriptionAr: 'أرنب لطيف مثالي لحفلات الشاي وبعد الظهيرة الدافئة. مناسب للمبتدئين مع دروس صورية خطوة بخطوة.',
    materials: ['Cotton DK yarn (200 m)', '3.5mm crochet hook', 'Polyfill stuffing', 'Safety eyes 10mm', 'Tapestry needle', 'Ribbon for bow'],
    materialsAr: ['خيط قطن DK (200 م)', 'إبرة كروشيه 3.5mm', 'حشوة بولي فيل', 'عيون أمان 10mm', 'إبرة خياطة', 'شريط للقوس'],
    yarnRecommendations: ['Lion Brand 24/7 Cotton', 'Paintbox Yarns Cotton DK', 'Scheepjes Catona'],
    yarnRecommendationsAr: ['Lion Brand 24/7 قطن', 'Paintbox قطن DK', 'Scheepjes Catona'],
  },
  {
    id: 'geometric-granny-blanket',
    title: 'Geometric Granny Blanket',
    titleAr: 'بطانية الجدة الهندسية',
    category: 'Blankets',
    categoryAr: 'البطانيات',
    difficulty: 'Beginner',
    difficultyAr: 'مبتدئ',
    hours: 20,
    yarnType: 'Worsted',
    yarnTypeAr: 'Worsted',
    hookSize: '5.0mm',
    finishedSize: '120 × 150 cm',
    finishedSizeAr: '120 × 150 سم',
    isPremium: false,
    favorites: 3200,
    createdAt: '2025-04-22',
    image: 'https://images.pexels.com/photos/5806996/pexels-photo-5806996.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop',
    gallery: [
      'https://images.pexels.com/photos/5806996/pexels-photo-5806996.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/6216236/pexels-photo-6216236.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/6463348/pexels-photo-6463348.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
    ],
    description: 'A modern take on the classic granny square blanket with bold geometric color blocks. Perfect for couch throws or baby gifts.',
    descriptionAr: 'نسخة عصرية من بطانية غراني سكوير الكلاسيكية بكتل لونية هندسية جريئة. مثالية كغطاء أريكة أو هدية للأطفال.',
    materials: ['Worsted yarn in 6 colors (1400 m total)', '5.0mm crochet hook', 'Stitch markers', 'Tapestry needle', 'Scissors'],
    materialsAr: ['خيط Worsted بـ 6 ألوان (1400 م)', 'إبرة كروشيه 5.0mm', 'علامات غرز', 'إبرة خياطة', 'مقص'],
    yarnRecommendations: ['Lion Brand Basic Stitch', 'Bernat Premium', 'Caron Simply Soft'],
    yarnRecommendationsAr: ['Lion Brand Basic Stitch', 'Bernat Premium', 'Caron Simply Soft'],
  },
  {
    id: 'cozy-autumn-throw',
    title: 'Cozy Autumn Throw',
    titleAr: 'غطاء الخريف الدافئ',
    category: 'Blankets',
    categoryAr: 'البطانيات',
    difficulty: 'Intermediate',
    difficultyAr: 'متوسط',
    hours: 28,
    yarnType: 'Bulky',
    yarnTypeAr: 'سميك',
    hookSize: '6.0mm',
    finishedSize: '130 × 170 cm',
    finishedSizeAr: '130 × 170 سم',
    isPremium: true,
    favorites: 1850,
    createdAt: '2025-07-25',
    image: 'https://images.pexels.com/photos/30373114/pexels-photo-30373114.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop',
    gallery: [
      'https://images.pexels.com/photos/30373114/pexels-photo-30373114.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/30373108/pexels-photo-30373108.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/35285968/pexels-photo-35285968.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
    ],
    description: 'A chunky, warm throw blanket with rich autumn tones. Uses a combination of post stitches for beautiful texture and warmth.',
    descriptionAr: 'غطاء سميك ودافئ بدرجات خريفية غنية. يستخدم مزيجًا من غرز الأعمدة لملمس جميل ودفء استثنائي.',
    materials: ['Bulky yarn in 4 autumn colors (1600 m)', '6.0mm crochet hook', 'Stitch markers', 'Tapestry needle', 'Scissors'],
    materialsAr: ['خيط سميك بـ 4 ألوان خريفية (1600 م)', 'إبرة كروشيه 6.0mm', 'علامات غرز', 'إبرة خياطة', 'مقص'],
    yarnRecommendations: ['Lion Brand Thick & Quick', 'Bernat Blanket Yarn', 'Noodles & Co Big Girl'],
    yarnRecommendationsAr: ['Lion Brand Thick & Quick', 'Bernat Blanket Yarn', 'Noodles & Co Big Girl'],
  },
  {
    id: 'sunbeam-beanie',
    title: 'Sunbeam Beanie',
    titleAr: 'قبعة أشعة الشمس',
    category: 'Hats',
    categoryAr: 'القبعات',
    difficulty: 'Beginner',
    difficultyAr: 'مبتدئ',
    hours: 4,
    yarnType: 'Worsted',
    yarnTypeAr: 'Worsted',
    hookSize: '5.0mm',
    finishedSize: 'Adult one-size',
    finishedSizeAr: 'مقاس موحد للكبار',
    isPremium: false,
    favorites: 980,
    createdAt: '2025-06-28',
    image: 'https://images.pexels.com/photos/9061918/pexels-photo-9061918.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop',
    gallery: [
      'https://images.pexels.com/photos/9061918/pexels-photo-9061918.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/14504995/pexels-photo-14504995.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/20549782/pexels-photo-20549782.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
    ],
    description: 'A cheerful yellow beanie with a fun character patch. Quick to make and perfect for gifting.',
    descriptionAr: 'قبعة صفراء مرحة بشخصية ممتعة. سريعة الصنع ومثالية كهدية.',
    materials: ['Worsted yarn (200 m)', '5.0mm crochet hook', 'Stitch marker', 'Tapestry needle', 'Optional: character patch'],
    materialsAr: ['خيط Worsted (200 م)', 'إبرة كروشيه 5.0mm', 'علامة غرز', 'إبرة خياطة', 'اختياري: رقعة شخصية'],
    yarnRecommendations: ['Lion Brand Basic Stitch', 'Red Heart Soft', 'Bernat Premium'],
    yarnRecommendationsAr: ['Lion Brand Basic Stitch', 'Red Heart Soft', 'Bernat Premium'],
  },
  {
    id: 'boho-crochet-hat',
    title: 'Boho Crochet Hat',
    titleAr: 'قبعة الكروشيه البوهيمية',
    category: 'Hats',
    categoryAr: 'القبعات',
    difficulty: 'Advanced',
    difficultyAr: 'متقدم',
    hours: 7,
    yarnType: 'Cotton DK',
    yarnTypeAr: 'قطن DK',
    hookSize: '4.0mm',
    finishedSize: 'Adult one-size',
    finishedSizeAr: 'مقاس موحد للكبار',
    isPremium: true,
    favorites: 720,
    createdAt: '2025-07-28',
    image: 'https://images.pexels.com/photos/36545529/pexels-photo-36545529.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop',
    gallery: [
      'https://images.pexels.com/photos/36545529/pexels-photo-36545529.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/36545528/pexels-photo-36545528.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/28232997/pexels-photo-28232997.png?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
    ],
    description: 'A bohemian-inspired crochet hat with intricate lacework. A statement piece for festivals and summer styling.',
    descriptionAr: 'قبعة كروشيه بوهيمية بعمل دانتيل معقد. قطعة مميزة للحفلات الصيفية وأزياء المهرجانات.',
    materials: ['Cotton DK yarn (250 m)', '4.0mm crochet hook', 'Stitch markers', 'Tapestry needle', 'Hat elastic band'],
    materialsAr: ['خيط قطن DK (250 م)', 'إبرة كروشيه 4.0mm', 'علامات غرز', 'إبرة خياطة', 'شريط مطاطي للقبعة'],
    yarnRecommendations: ['Lion Brand 24/7 Cotton', 'Paintbox Yarns Cotton DK', 'Scheepjes Catona'],
    yarnRecommendationsAr: ['Lion Brand 24/7 قطن', 'Paintbox قطن DK', 'Scheepjes Catona'],
  },
  {
    id: 'multicolor-scarf',
    title: 'Multicolor Autumn Scarf',
    titleAr: 'وشاح الخريف متعدد الألوان',
    category: 'Scarves',
    categoryAr: 'الوشاح',
    difficulty: 'Beginner',
    difficultyAr: 'مبتدئ',
    hours: 5,
    yarnType: 'DK',
    yarnTypeAr: 'DK',
    hookSize: '4.0mm',
    finishedSize: '20 × 150 cm',
    finishedSizeAr: '20 × 150 سم',
    isPremium: false,
    favorites: 1340,
    createdAt: '2025-05-18',
    image: 'https://images.pexels.com/photos/28949622/pexels-photo-28949622.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop',
    gallery: [
      'https://images.pexels.com/photos/28949622/pexels-photo-28949622.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/35739748/pexels-photo-35739748.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/10453392/pexels-photo-10453392.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
    ],
    description: 'A vibrant multicolor scarf perfect for autumn. Uses simple stitches with self-striping yarn for stunning results.',
    descriptionAr: 'وشاح متعدد الألوان نابض بالحياة مثالي للخريف. يستخدم غرزًا بسيطة مع خيط مخطط ذاتيًا لنتائج مذهلة.',
    materials: ['DK self-striping yarn (300 m)', '4.0mm crochet hook', 'Tapestry needle', 'Scissors'],
    materialsAr: ['خيط DK مخطط ذاتيًا (300 م)', 'إبرة كروشيه 4.0mm', 'إبرة خياطة', 'مقص'],
    yarnRecommendations: ['Caron Cakes', 'Lion Brand Mandala', 'Bernat Pop!'],
    yarnRecommendationsAr: ['Caron Cakes', 'Lion Brand Mandala', 'Bernat Pop!'],
  },
  {
    id: 'hanging-crochet-bags',
    title: 'Hanging Crochet Bags Set',
    titleAr: 'مجموعة حقائب الكروشيه المعلقة',
    category: 'Bags',
    categoryAr: 'الحقائب',
    difficulty: 'Intermediate',
    difficultyAr: 'متوسط',
    hours: 8,
    yarnType: 'Cotton Worsted',
    yarnTypeAr: 'قطن Worsted',
    hookSize: '4.5mm',
    finishedSize: '3 sizes (S/M/L)',
    finishedSizeAr: '3 مقاسات (ص/م/ك)',
    isPremium: true,
    favorites: 640,
    createdAt: '2025-07-30',
    image: 'https://images.pexels.com/photos/38791655/pexels-photo-38791655.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop',
    gallery: [
      'https://images.pexels.com/photos/38791655/pexels-photo-38791655.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/33207480/pexels-photo-33207480.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/30859912/pexels-photo-30859912.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
    ],
    description: 'A set of three hanging crochet bags with intricate patterns. Perfect for market displays, home organization, or gifts.',
    descriptionAr: 'مجموعة من ثلاث حقائب كروشيه معلقة بأنماط معقدة. مثالية لعرض السوق أو تنظيم المنزل أو كهدية.',
    materials: ['Cotton Worsted yarn (500 m)', '4.5mm crochet hook', 'Wooden rings for hanging', 'Stitch markers', 'Tapestry needle'],
    materialsAr: ['خيط قطن Worsted (500 م)', 'إبرة كروشيه 4.5mm', 'حلقات خشبية للتعليق', 'علامات غرز', 'إبرة خياطة'],
    yarnRecommendations: ['Lion Brand 24/7 Cotton', 'Paintbox Yarns Cotton Aran', 'Sugar Bush Cotton'],
    yarnRecommendationsAr: ['Lion Brand 24/7 قطن', 'Paintbox قطن Aran', 'Sugar Bush قطن'],
  },
  {
    id: 'bathroom-storage-baskets',
    title: 'Bathroom Storage Baskets',
    titleAr: 'سلال تخزين الحمام',
    category: 'Home Decor',
    categoryAr: 'ديكور المنزل',
    difficulty: 'Beginner',
    difficultyAr: 'مبتدئ',
    hours: 3,
    yarnType: 'Cotton Bulky',
    yarnTypeAr: 'قطن سميك',
    hookSize: '6.0mm',
    finishedSize: '10/15/20 cm diameter',
    finishedSizeAr: 'قطر 10/15/20 سم',
    isPremium: false,
    favorites: 1100,
    createdAt: '2025-06-05',
    image: 'https://images.pexels.com/photos/5264802/pexels-photo-5264802.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop',
    gallery: [
      'https://images.pexels.com/photos/5264802/pexels-photo-5264802.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/5602985/pexels-photo-5602985.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/5602980/pexels-photo-5602980.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
    ],
    description: 'A nesting set of three cotton baskets for bathroom storage. Quick to make and perfect for organizing cotton pads, soaps, and toiletries.',
    descriptionAr: 'مجموعة من ثلاث سلال قطنية متداخلة لتخزين الحمام. سريعة الصنع ومثالية لتنظيم قطن التنظيف والصابون ومستلزمات الحمام.',
    materials: ['Cotton Bulky yarn (300 m)', '6.0mm crochet hook', 'Stitch markers', 'Tapestry needle'],
    materialsAr: ['خيط قطن سميك (300 م)', 'إبرة كروشيه 6.0mm', 'علامات غرز', 'إبرة خياطة'],
    yarnRecommendations: ['Lion Brand 24/7 Cotton', 'Bernat Maker Home Dec', 'Paintbox Yarns Cotton Aran'],
    yarnRecommendationsAr: ['Lion Brand 24/7 قطن', 'Bernat Maker Home Dec', 'Paintbox قطن Aran'],
  },
  {
    id: 'yarn-storage-basket',
    title: 'Yarn Storage Basket',
    titleAr: 'سلة تخزين الخيوط',
    category: 'Home Decor',
    categoryAr: 'ديكور المنزل',
    difficulty: 'Intermediate',
    difficultyAr: 'متوسط',
    hours: 6,
    yarnType: 'T-shirt Yarn',
    yarnTypeAr: 'خيط التيشيرت',
    hookSize: '10.0mm',
    finishedSize: '25 × 30 cm',
    finishedSizeAr: '25 × 30 سم',
    isPremium: true,
    favorites: 540,
    createdAt: '2025-07-15',
    image: 'https://images.pexels.com/photos/5788488/pexels-photo-5788488.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop',
    gallery: [
      'https://images.pexels.com/photos/5788488/pexels-photo-5788488.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/6634688/pexels-photo-6634688.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
      'https://images.pexels.com/photos/5603193/pexels-photo-5603193.jpeg?auto=compress&cs=tinysrgb&w=900&h=1100&fit=crop',
    ],
    description: 'A large, sturdy basket made from T-shirt yarn for storing yarn skeins, WIPs, or household items. Works up quickly with a large hook.',
    descriptionAr: 'سلة كبيرة متينة من خيط التيشيرت لتخزين خيوط الكروشيه أو المشاريع قيد العمل أو أدوات المنزل. تُعمل بسرعة بإبرة كبيرة.',
    materials: ['T-shirt yarn (400 m)', '10.0mm crochet hook', 'Stitch markers', 'Tapestry needle'],
    materialsAr: ['خيط التيشيرت (400 م)', 'إبرة كروشيه 10.0mm', 'علامات غرز', 'إبرة خياطة'],
    yarnRecommendations: ['Hoooked Zpagetti', 'Bernat Maker Big', 'Lion Brand Flikke'],
    yarnRecommendationsAr: ['Hoooked Zpagetti', 'Bernat Maker Big', 'Lion Brand Flikke'],
  },
];
